### ISSUE TITLE
Protótipo de tela de Ajuda

### ISSUE THREAD

**Issue by Ma145** [enzomoralesl/FutMobile#10]

**Comment by vgenerato** [comment]
Tela de ajuda foi feita e contém 3 abas, sendo elas: Ajuda, Sobre e Contato.

**Comment by Ma145** [comment]
- Inicio: https://github.com/enzomoralesl/FutMobile/commit/3ce6a8fd39d069bd806af45f912d0f2faa29b990

- Término: https://github.com/enzomoralesl/FutMobile/commit/dff778652c8f074f637b5193d586fd0cff03f943

> Agradecimentos a @vgenerato e a @enzomoralesl.
> Att,
> Marcelo Silva.
