### ISSUE TITLE
Criação do feed principal de notícias

### ISSUE THREAD

**Issue by Ma145** [enzomoralesl/FutMobile#13]
Implementação do feed de notícias na tela conectando front-end com o banco de dados pelo back-end.

**Comment by Ma145** [comment]
Começo da implementação do feed de noticias e comentários: https://github.com/enzomoralesl/FutMobile/commit/019ab775afd0f1a045d340a15c9e3171a989b742

**Comment by vgenerato** [comment]
A aba de notícias conta com:
- Publicação, edição, deleção e like de posts;
- Publicação, edição, deleção e like de comentários (relacionados aos posts);

Desenvolvimento da issue:
- Primeiro foi implantado a inteligência do back-end. No qual pode armazenar, atualizar e retornar à tela todas as informações;
- Em seguida foi realizado o front-end, adicionando estilos e design relacionados à marca "FutMobile";

**Comment by vgenerato** [comment]
Commit relacionados:
- Issue resolvida: https://github.com/enzomoralesl/FutMobile/commit/032299fa74f17cca77ec1a4c64cc255693c6c9e6
- Pull request: https://github.com/enzomoralesl/FutMobile/commit/6f8d8704bf0f69fae3413377d65b5b72b4f96a4a

Agradecimentos a @Ma145, @enzomoralesl e @Vitor-soares-silva .
Att,
Victor Generato.
