### ISSUE TITLE
Serviço de postagens pelo cliente

### ISSUE THREAD

**Issue by Ma145** [enzomoralesl/FutMobile#14]
Implementação do serviço de postagens do usuário cliente na aplicação.

**Comment by vgenerato** [comment]
O serviço de postagem pelo cliente consiste na criação da inteligência por trás do feed principal de notícias.

Desenvolvimento:
- O desenvolvimento foi realizado junto à issue #13;
- Como uma issue é relacionada a outra, foi utilizada a mesma branch para desenvolvimento.

**Comment by vgenerato** [comment]
Commit relacionados:

Issue resolvida: 032299f
Pull request: 6f8d870

Agradecimentos a @Ma145, @enzomoralesl e @Vitor-soares-silva .
Att,
Victor Generato.
