### ISSUE TITLE
Finalização das telas

### ISSUE THREAD

**Issue by Vitor-soares-silva** [enzomoralesl/FutMobile#18]
Conclusão das telas inacabadas.

**Comment by vgenerato** [comment]
- Campeonatos
A tela de campeonatos conta, inicialmente, com uma tela de filtragem de torneios, ao selecionar o torneiro desejado, o usuário é redirecionado para uma tela com os detalhes do mesmo. O usuário administrador poderá editar e deletar um campeonato, o usuário comum poderá sugerir a edição ou deleção de um campeonato.

- Times
A tela de times conta, inicialmente, com uma tela de filtragem de clubes, ao selecionar o clube desejado, o usuário é redirecionado para uma tela com os detalhes do mesmo. O usuário administrador poderá editar e deletar um time, o usuário comum poderá sugerir a edição ou deleção de um time.

**Comment by vgenerato** [comment]
Commit relacionados:

Issue resolvida: c2a51f3fafbc10ca2053a06ed5113e67d5669dc6
Pull request: 79abf8eda23a2ee30f169a5887819fcd23b346d8

Agradecimentos a @Ma145.
Att,
Victor Generato.
