### ISSUE TITLE
Criação de API

### ISSUE THREAD

**Issue by Ma145** [enzomoralesl/FutMobile#32]
Esta issue tratará sobre a criação de uma API REST (RESTful/Representational State Transfer) para o sistema FutMobile.
Possibilitando a:

- Listagem de usuários contendo **algumas** de suas informações (**apenas para Administradores**);
- Listagem e possibilidade de edição e remoção de posts;
- Listagem e possibilidade de edição e remoção de times;
- Listagem e possibilidade de edição e remoção de campeonatos;

**Comment by Ma145** [comment]
Nesta primeira parte (https://github.com/enzomoralesl/FutMobile/commit/818533b0afce9b3b961202cfe39fc88d79e62dce) foram criadas as funções de:

- Listagem de usuários (apenas para Administradores);
- Listagem e possibilidade de edição e remoção de posts;

**Comment by vgenerato** [comment]
Issue pausada para finalização do projeto.
